### ISSUE TITLE
pitest-df Azure Data Factory cannot access pitestdatasa

### ISSUE THREAD

**Issue by bryan-skylight** [CDCgov/prime-public-health-data-infrastructure#108]
**Describe the bug**
The `pitest-df` Azure Data Factory resource is used to ingest new data from Virginia's SFTP server. To do this, it connects to the SFTP server and copies the data into the `pitestdatasa` storage account. This was previously working because we were using connection strings, but now that we've moved to managed identities, the ADF resource no longer has permissions.

To remedy this, I believe the managed identity for `pitest-df` should have the same permissions that have been granted to the `pitest-python-functionapp`'s managed identity with regard to the `pitestdatasa` storage account.

**Impact**
Because the ADF resource cannot access the storage account, new data from Virginia cannot be ingested into our environment, which is problematic for two reasons:
1. It prevents us from using this new data in our work to test edge cases, capacity, and record linkage  
2. Virginia only holds their data for 18 days, so if we don't ingest the data in a timely fashion we lose that data

**To Reproduce**
1. Log in to the PHDI Azure portal
3. Access the `pitest-df` resource
4. Open Azure Data Factory Studio
5. Click "Ingest" tab in center of screen on "Home" tab
6. Click the Next button
7. Choose `vdhsftp` option from "Connection" drop down menu
8. If "Interactive Authoring" is not enabled, enable it by:
    a. Clicking "Edit" next to the "Integration Runtime" drop down menu  
    b. Clicking the "Virtual Network" tab  
    c. Clicking the "Enable" radio button under "Interactive authoring"
9. Type "ELR/" for the "File or folder"
10. Make sure "Binary copy" and "Recursively" are selected under options
11. Click Next
12. Choose `pitestdatastorage`
13. See error "connection failed"

**Expected behavior**
The test connection for the `pitestdatastorage` should return a successful connection indicating that the ADF can communicate with the storage container.

**Comment by bryan-skylight** [comment]
Based on conversations in Slack, and the comments left here, I have updated the `data.tf` file (see [PR#110](https://github.com/CDCgov/prime-public-health-data-infrastructure/pull/110)) to add a new container to the list of containers `pitest-df` has permissions to access. Can you please apply these changes to our environment?

**Comment by JosiahSiegel** [comment]
Permissions applied

**Comment by JosiahSiegel** [comment]
Adding the Data Lake linked service to data factory and I'm able to transfer the files from SFTP. [link](https://semanticbits.slack.com/archives/C02TRFPBFJN/p1652795682832829?thread_ts=1652735243.318389&cid=C02TRFPBFJN)
