### ISSUE TITLE
Clean up Github workflows

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-public-health-data-infrastructure#164]
As a devops engineer I want to understand which actions are related to testing versus deployment versus utilities. 

* Delete the build_docker workflow, it is redundant
* change the name of "build_hub.yml" `:name` to Build Hub (instead of Router)
* Remove production from "build_hub.yml"'s `on:` statement
* Rename release.yml to "release_to_azure.yml"
* Rename github_release.yaml to release_to_github.yml

**Comment by lucasdze** [comment]
PR https://github.com/CDCgov/prime-reportstream/pull/6584 has been created to resolve this issue
